name: my_own_space
description: "Open-Source Private Cloud App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  mime: 2.0.0
  http: ^1.2.2
  http_parser: ^4.0.0
  sqlite3: 2.5.0
  sqlite3_flutter_libs: ^0.5.28
  path: ^1.8.0
  path_provider: 2.1.5
  file_picker: ^8.1.7
  dio: ^5.7.0
  intl: ^0.18.0
  material_design_icons_flutter: ^7.0.7296
  flutter_oss_licenses: ^2.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true

