// VERSION 1.0 OF MY_OWN_SPACE:
  // dev: M.C.A
  // WHEN A TASK IS COMPLETED , IT WILL BE MARKED WITH *DONE*

  /*

      INTERFATA USER TERMINATA , MAI RAMANE SETARILE , 3 OPTIUNI SIMPLE DE ADAUGAT SI ATAT;

  */